version: '3.8'

services:
  db:
    image: postgres:17 # You can change the version if needed
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: poloneix
    ports:
      - "5432:5432"  # Exposing the PostgreSQL default port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    restart: always

volumes:
  postgres_data:
